### ISSUE TITLE
Pin toggle after deepSleep

### ISSUE THREAD

**Issue by rwalli** [coolibre/thermomat#45]
Sorry for opening an issue here,

I'v exactly the same hardware setup and had problems after sleep:
"ESP.deepSleep(10*1000000)" toggles the pins and sometimes the value at the display changes without interaction.
As I read in many articles, pin change after deep sleep is "normal" and can't be avoided.

Do you know why it works in your setup?

Robert

**Comment by coolibre** [comment]
Hi, opening issues here is wanted!!! I have no much time at all to really work on the code. So with opening issues I can fokus on whats really needs to be improved.

To understand your problem right: The pinchange on wakeup leads to a wrong temperature after the pulse function? Or does it then not even work to send inputs onto the encoder pins?

To be honest i didn't put much effort into the device side, as it was working with the provided code in acceptable fashion.

**Comment by rwalli** [comment]
> 
> To understand your problem right: The pinchange on wakeup leads to a wrong temperature after the pulse function?

Not exactly,  the temperature changes without pulse function. Only because of random pin change at wake up.
( It's documented here: https://www.esp8266.com/viewtopic.php?f=5&t=11282 )

> Or does it then not even work to send inputs onto the encoder pins? Are you using my code or is it a general question?

I use parts of your code (the idea with the rotary encoder and the pulse function) and the ESP.deepSleep - function which i guess rises the problem.
My code is running now for more than a week without problem with "light-sleep".
When i switch to "deep-sleep" the temperature is changing on the EQ-3 randomly.
Sometimes 0.5C up sometimes down. Once i had bad luck and it went to zero slowly... 
Do you have the same temperature on the eq-3 when the pulse function is not used for a longer period? 

> I guess in my scenario here even a pin toggle would not effect the functionality because the code triggers the value on the thermostat to zero and then up to the server configured temperature. So even if the pin change corrupts the value it's straight away taken to 0 and the intermediate wrong input makes no difference.

I understand, but it will drift if the pulse function is not used for a while...

Do you update the temperature every 15 minutes?

Robert

**Comment by coolibre** [comment]
Hi Robert,

correct. The process in my use case is wakeup - request current temperature from server - pulse to zero and beyond (60 steps) - pulse up to temperature- sleep 15 mins. Due to the speed the pulse happens I guess I didn't even recognize a pin changes during wakeup. And I guess I really have the changes as well. They simply don't bother me due to the use case. While sleeping the temperature stays exactly the same.

**Comment by rwalli** [comment]
> correct. The process in my use case is wakeup - request current temperature from server - pulse to zero and beyond 

Thank you for clarifying this!
I will go for your concept (pulse to zero and up after sleep) because light_sleep (which takes approx. 600uA in my case) and optimizing "online time" to 300ms empty the NiCd Accu's in about 1 month.
